### PR TITLE
Add link to web app code pattern

### PR DESCRIPTION
**Pull request by ajbozarth**
Add a README section linking to the example web app.

### CODE REVIEW

**Comment by ajbozarth** [comment]
I've made a couple updates and put in the link to the code pattern that will work once it's live. This is good to merge once the pattern is published as long as everyone is ok with the text

**Comment by djalova** [comment]
LGTM

**Comment by ajbozarth** [comment]
@lresende this can't be merged yet the code pattern isn't published, this was a WIP

**Comment by ajbozarth** [comment]
nvm, it'll be published within the next 24hr so I guess its fine

**Pull request merged**
