### PR TITLE
Update the Kube yaml file

### PR DESCRIPTION
**Pull request by ajbozarth**
This updates the yaml file for deploying to Kube to be cleaner and follow standard practices.

- I'll be adding documentation on using this in the README in another PR
- This update changes how the model is deployed on Kube
   - Using a `Deployment` rather than a `Pod` is standard good practice and redundancy
- This also standardizes the naming conventions to be the repo name in lower-case to match the docker hub naming

This PR is a first step in https://github.ibm.com/CODAIT/Usability-Enhancement/issues/2 and is being proposed first since the parallel update to the web app depends on it.

### CODE REVIEW

**Comment by ajbozarth** [comment]
A few follow up points on this.
- I'll be adding documentation on using this in the README in another PR
- This update changes how the model is deployed on Kube
   - Using a `Deployment` rather than a `Pod` is standard good practice and redundancy
   - Using a `LoadBalancer` type `Service` rather than `NodePort` will automatically surface the API to the expected external port `5000` without extra steps.
- This also standardizes the naming conventions to be the repo name in lower-case to match the docker hub naming

**Comment by djalova** [comment]
Running the file works for me

**Comment by ajbozarth** [comment]
I updated the PR description to include by previous comment.

I've also opened a PR on MAX-skeleton with a template based on this yaml file. 
https://github.ibm.com/CODAIT/MAX-skeleton/pull/10

**Comment by MLnick** [comment]
LGTM

**Comment by ajbozarth** [comment]
Based on @ptitzler feedback and scrum discussion I've changed `LoadBalancer` back to `NodePort` to allow for use on IBM Cloud free tier

**Pull request merged**
